import type { Metadata } from "next";
import ButtonHome from "../components/shared/button_home";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div>
            {children}
            <div className="fixed bottom-4 left-1/2 -translate-x-1/2 md:left-6 md:translate-x-0">
                <ButtonHome />
            </div>
        </div>
    );
}
